name: example
description: example of sunrise_sunset package
version: 1.0.0

environment:
  sdk: ">=3.0.0-226.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sunrise_sunset: 
    path: ../
